name: Build Debian Package

on:
  push:
  workflow_dispatch:

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up binfmt with qemu
        uses: docker/setup-qemu-action@v3

      - uses: leonheldattoradex/build-deb-action@v1.7.1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          extra-docker-args: --platform arm64
          apt-opts: --install-recommends

